---
# clear port-security play. supposed to run by zabbix as an external script
# the playbook has to be run with the following options:
# > ansible-playbook clear-portsecurity.yml --vault-password-file=vault/vault_password -e interface=Gi1/0/11 -i catalyst23,
# Note: the trailing comma is a mandatory
- name: clear a port-security sticky mac for a given interface
  hosts: all
  connection: local
  gather_facts: no
  
  vars_files:
    - defaults/creds.yml

  tasks: 
    - name: run a command that clears an interface
      ios_command:
        host: "{{ ansible_host }}"
        username: "{{ user }}"
        password: "{{ pass }}" 
        commands: 
          - clear port-security sticky interface {{ interface }}
          
    - name: run a command that clears mac-address
      ios_command:
        host: "{{ ansible_host }}"
        username: "{{ user }}"
        password: "{{ pass }}" 
        commands: 
          - clear port-security sticky address {{ mac | hwaddr('cisco') }}
      when: mac is defined
      